### ISSUE TITLE
Plugin unloading then load broken on Paper 1.20.2

### ISSUE THREAD

**Issue by codeHusky** [TheBlackEntity/PlugManX#26]
Plugins fail to unload and load back in on 1.20.2 when previously possible on 1.19.x and lower.

```
> plugman list
[22:03:35 INFO]: [PlugMan] Plugins (57): [...] PlugManX, [...] SubserverTools, [...]
> plugman unload SubserverTools
[22:03:39 INFO]: [SubserverTools] Disabling SubserverTools v1.0-SNAPSHOT
[22:03:39 INFO]: [PlugMan] SubserverTools has been unloaded.
> plugman load StreamerTools-1.0-SNAPSHOT
[22:03:47 WARN]: Unexpected exception while parsing console command "plugman load StreamerTools-1.0-SNAPSHOT"
org.bukkit.command.CommandException: Unhandled exception executing command 'plugman' in plugin PlugManX v2.3.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[huskypaper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[huskypaper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"32c1dcd"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:974) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"32c1dcd"]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"32c1dcd"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"32c1dcd"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"32c1dcd"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"32c1dcd"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"32c1dcd"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.onLoad()" because "target" is null
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:308) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:120) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[huskypaper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

**Comment by TheBlackEntity** [comment]
Please update to the latest version and see if that fixes it

**Comment by codeHusky** [comment]
My bad, could’ve sworn I was on 2.3.5. Must’ve just uploaded it in the wrong spot. Works on latest build, thanks.
