### ISSUE TITLE
I got this error on git-Purpur-2062 (MC: 1.20.1)*

### ISSUE THREAD

**Issue by itzyongan** [TheBlackEntity/PlugManX#29]
org.yaml.snakeyaml.error.YAMLException: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:214) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:172) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:167) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:122) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1204) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:320) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:212) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:156) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:434) ~[snakeyaml-2.0.jar:?]
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:327) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.PlugMan.onEnable(PlugMan.java:307) ~[PlugManX (2).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:929) ~[?:?]
        at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:940) ~[?:?]
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:457) ~[?:?]
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:?]
        at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
        at java.io.PushbackInputStream.read(PushbackInputStream.java:182) ~[?:?]
        at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:85) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:117) ~[snakeyaml-2.0.jar:?]
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:179) ~[snakeyaml-2.0.jar:?]
        ... 25 more
[14:54:21 INFO]: [PlugManX] Disabling PlugManX v2.3.5

**Comment by TheBlackEntity** [comment]
Please make sure you don't have any corrupt jar files in your plugins directory.


I'm currently in a hospital, so I can't add another check to prevent this issue in the first place right now.

Sorry for the inconvenience

**Comment by itzyongan** [comment]
> Please make sure you don't have any corrupt jar files in your plugins directory.
> 
> I'm currently in a hospital, so I can't add another check to prevent this issue in the first place right now.
> 
> Sorry for the inconvenience

I’ve found the plugin that makes PlugmanX disabled, thanks you!
