### ISSUE TITLE
get a warn from Paper with CB packge relocation

### ISSUE THREAD

**Issue by YuanYuanOwO** [TheBlackEntity/PlugManX#35]
https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/
```
[20:07:44 WARN]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[20:07:44 WARN]: It seems like you're running on paper.
[20:07:44 WARN]: PlugManX cannot interact with paper-plugins, yet.
[20:07:44 WARN]: Also, if you encounter any issues, please join my discord: https://discord.gg/GxEFhVY6ff
[20:07:44 WARN]: Or create an issue on GitHub: https://github.com/TheBlackEntity/PlugMan
[20:07:44 WARN]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[20:07:44 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
[20:07:44 WARN]:        at PlugManX.jar//com.rylinaux.plugman.util.BukkitCommandWrap.<init>(BukkitCommandWrap.java:29)
[20:07:44 WARN]:        at PlugManX.jar//com.rylinaux.plugman.PlugMan.onEnable(PlugMan.java:267)
[20:07:44 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[20:07:44 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[20:07:44 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[20:07:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[20:07:44 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639)
[20:07:44 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:550)
[20:07:44 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275)
[20:07:44 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1133)
[20:07:44 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[20:07:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by TheBlackEntity** [comment]
That's... Kinda annoying...

I'll look into it.
But I'll probably just stop developing PlugManX if Paper keeps adding breaking changes for no reason...

**Comment by seema84** [comment]
I am sure that Paper has reasons for this.
It would be a real shame if you stopped developing. :(
